/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <android/log.h>
/* Header for class com_example_ndkfileoperate_NDKFileUtils */

#ifndef _Included_com_example_ndkfileoperate_NDKFileUtils
#define _Included_com_example_ndkfileoperate_NDKFileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkfileoperate_NDKFileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkfileoperate_NDKFileUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_example_ndkfileoperate_NDKFileUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkfileoperate_NDKFileUtils_patch
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
